server:
  port: 8080
spring:
  application:
    name: recommender
  data:
    mongodb:
      host: 47.93.97.16
      uri: mongodb://47.93.97.16:27017
      database: recommender
#    authentication-database: admin
  redis:
    database: 0
    port: 6379
    host: 47.93.97.16
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0

